name: flutter_practopic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  go_router: ^14.2.0
  slow_fib_ffi:
    path: "./packages/slow_fib_ffi"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - "images/image-1.jpg"
    - "images/image-2.jpg"

  shaders:
    - "shaders/simple.frag"
    - "shaders/toy_gradient.frag"
    - "shaders/toy_mozice.frag"
    - "shaders/image_flip.frag"
    - "shaders/ripple.frag"
